### ISSUE TITLE
Write tutorial for detection of mitoflashes

### ISSUE THREAD

**Issue by kostrykin** [beatrizserrano/galaxy-image-community#7]
There is a workflow for detection of mitoflashes: https://usegalaxy.eu/published/workflow?id=ffa80e0637d079f2

A mitoflash is a fluorescence intensity burst from mitochondria (a temporal intensity peak).

![Image](https://github.com/user-attachments/assets/45a23355-4a86-41fa-a1dd-15a105cc8add)

And there is also a paper about it: [Wang et al., Pain 2022](https://doi.org/10.1097/j.pain.0000000000002642)

Given the paper, writing the tutorial should be kind of straight-forward.

---

**Things to be done:**
- [x] Check whether we have data suitable for this workflow? Preferably, use the data from the paper.
- [x] Write the tutorial which covers the reproduction and usage of the workflow.

**Comment by dianichj** [comment]
I would like to work on this issue. Could someone assign it to me or give me permission? Thanks a lot!

**Comment by dianichj** [comment]
> There is a workflow for detection of mitoflashes: https://usegalaxy.eu/published/workflow?id=ffa80e0637d079f2
> A mitoflash is a fluorescence intensity burst from mitochondria (a temporal intensity peak).
> And there is also a paper about it: [Wang et al., Pain 2022](https://doi.org/10.1097/j.pain.0000000000002642)
> 
> Given the paper, writing the tutorial should be kind of straight-forward.
> 
> **Things to be done:**
> 
> * [X]  Check whether we have data suitable for this workflow? Preferably, use the data from the paper.
> * [ ]  Write the tutorial which covers the reproduction and usage of the workflow.

**Comment by kostrykin** [comment]
Example from the original data:
![Image](https://github.com/user-attachments/assets/bc5b82ff-d7f5-48a3-b92b-08846125eb49)

See the yellow section in the screenshot if you have trouble seeing where it occurs.

**Comment by dianichj** [comment]
Related to #5514

**Comment by beatrizserrano** [comment]
This is now done, so I'll close the issue. Thanks a lot @dianichj and @kostrykin 💟
